### PR TITLE
Fixed the roomfinder-cross-bug

### LINKED ISSUE #323: [Bug] Cross not at the right place when resizing the window
**Describe the bug**
When you resize the window the cross of the roomfinder map is not at the right place anymore.

**To Reproduce**

1. Go to any room
2. Click on roomfinder
3. Make your browser-window smaller 
4. The cross is at a wrong place

**Expected behavior**
The cross should stay at the right place when resizing the window.

**Screenshots**

_Fullscreen_ 
grafik

_Smaller Window_
grafik

**Desktop:**

- OS: Windows 11
- Browser: Mozilla Firefox
- Version 107.0 (64-bit)

### PR DESCRIPTION
**Pull request by Marius1501**
Fixes #323 

## Proposed Changes (include Screenshots if possible)

- Now it updates the cross position when the browser-window is resized
- For the main-roomfinder and the modal-roomfinder

At fullsize:
grafik

At smaller size:
grafik

## How to test this PR

1. Go to any roomfinder-map or to any modal-roomfinder
2. Resize your browser-window to any size
3. See that the cross stays at the same place

## How has this been tested?

- Windows 11
- Firefox Version 108.0.2 (64-Bit)

## Checklist:

- [x] I have updated the documentation / No need to update the documentation
- [x] I have run the linter

### CODE REVIEW

File: webclient/src/views/view/view-view.js [hunk 1]
```diff
@@ -662,6 +662,10 @@ navigatum.registerView("view", {
     };
     window.addEventListener("storage", updateCoordinateCounter);
     updateCoordinateCounter();
+    window.addEventListener('resize', () => {
```
Comment (CommanderStorm) [inline webclient/src/views/view/view-view.js:665]:
```suggestion
    window.addEventListener("resize", () => {
```

**Review by CommanderStorm — APPROVED** [review]
