### PR TITLE
Better 404 handling for missing rooms

### LINKED ISSUE #519: [Bug] Wrong 404 handling
If a user enteres a link like https://nav.tum.de/room/2906.05.016d which does not exist, the 404 page is not shown, since this page is valid to the router.

### PR DESCRIPTION
**Pull request by CommanderStorm**
Fixes #519 
The current implementation has the downside of urlencoding the path, but I think this shuld be acceptable

## Proposed Changes (include Screenshots if possible)

- Removes unused `options` option
- Adds a handler for routes which should show 404 which shows 404

## How to test this PR

1. (once #200 is merged) look at it in the staging
2. code review

## How has this been tested?

- with local staging going to http://localhost:8000/room/2906.05.016d
- get redirected to http://localhost:8000/room%2F2906.05.016d and see 
  image

## Checklist:

- [x] I have updated the documentation / No need to update the documentation
- [x] I have run the linter

### CODE REVIEW

**Comment by octycs** [comment]
I fixed the urlencoding and a bug that the feedback from did not open when clicking on it. I think this can be merged now.

File: webclient/src/views/NotFoundView.vue [hunk 1]
```diff
@@ -2,14 +2,15 @@
...
+const href = window.location.href;
 </script>
 
 <template>
   <div class="toast toast-error">{{ $t("core_js.error.404") }}</div>
   <h5 style="margin-top: 25px">{{ $t("view_404.header") }}</h5>
   <p>{{ $t("view_404.description") }}</p>
   <button
-    @click="global.openFeedback('bug', `404 on ${window.location.href}`, $t('view_404.got_here'))"
+    @click="global.openFeedback('bug', `404 on ${href}`, $t('view_404.got_here'))"
```
Comment (CommanderStorm) [inline webclient/src/views/NotFoundView.vue:13]:
```suggestion
    @click="global.openFeedback('bug', `404 on ${window.location.href}`, $t('view_404.got_here'))"
```
I think this could point to the wrong site (`script setup` is only executed once)

File: webclient/src/views/NotFoundView.vue [hunk 2]
```diff
@@ -2,14 +2,15 @@
 import { useGlobalStore } from "@/stores/global";
 
 const global = useGlobalStore();
+const href = window.location.href;
```
Comment (CommanderStorm) [inline webclient/src/views/NotFoundView.vue:5]:
```suggestion
```
